### ISSUE TITLE
【图像自定义问题】

### ISSUE THREAD

**Issue by Nuts-sugar** [Lete114/CardLink#1]
请问这里可以对卡片链接的图片进行自定义操作吗

**Comment by lete114** [comment]
不可以

**Comment by lete114** [comment]
不过我觉得这是个很不错的想法，会考虑支持自定义图标，但现在还没有思路

**Comment by lete114** [comment]
你可以通过提前预设指定网站信息，来达到自定义图片的操作

举例:
```js
const site = 'https://www.imlete.cn/'
cardLink.cache[site] = {}
cardLink.cache[site].title = 'Lete乐特'
cardLink.cache[site].link = site
cardLink.cache[site].icon= 'https://www.imlete.cn/img/avatar.png'

// 自定义预设后开始渲染
cardLink()
```

**Comment by Nuts-sugar** [comment]
嗯嗯 明白！谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月17日(星期三) 中午11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lete114/CardLink] 【图像自定义问题】 (Issue #1)





 
你可以通过提前预设指定网站信息，来达到自定义图片的操作
 
举例:
 const site = 'https://www.imlete.cn/' cardLink.cache[site] = {} cardLink.cache[site].title = 'Lete乐特' cardLink.cache[site].link = site cardLink.cache[site].icon= 'https://www.imlete.cn/img/avatar.png' // 自定义预设后开始渲染 cardLink()
