### ISSUE TITLE
使用参数控制生成不同大小的卡片以用来不同的用途

### ISSUE THREAD

**Issue by appotry** [Lete114/CardLink#2]
很棒的插件

如果有参数控制生成不同大小，样式的卡片就更好了

看一下这篇文章的url卡片 就挺漂亮的

<https://sleele.com/2020/03/16/%e9%ab%98%e9%98%b6%e6%95%99%e7%a8%8b-%e8%bf%bd%e5%89%a7%e5%85%a8%e6%b5%81%e7%a8%8b%e8%87%aa%e5%8a%a8%e5%8c%96/>

**Comment by lete114** [comment]
我觉得这篇文章的url卡片并不好，有一股广告的感觉

至于想自定义不同大小卡片样式的，可以通过自定义css来覆盖掉默认的css样式

**Comment by appotry** [comment]
卡片本身就有一种广告的意味，插入大型卡片打广告没啥问题

精简卡片 最基本信息自动获取

中大型卡片，显示更多链接文章，站点描叙信息

不光是CSS的问题，更多的是显示信息量的多寡来区分卡片大小

**Comment by lete114** [comment]
这与本仓库的初中不符合，最初只是为了让网站上的链接不那么单调，使它变成卡片式链接会提高用户的注意力点击率等，并不想过多展示链接网站的太多信息而导致影响了自己网站的内容

**Comment by appotry** [comment]
> 这与本仓库的初中不符合，最初只是为了让网站上的链接不那么单调，使它变成卡片式链接会提高用户的注意力点击率等，并不想过多展示链接网站的太多信息而导致影响了自己网站的内容

可以通过a标签属性来控制显示的信息量大小么，有的链接想精简展示，但有的链接，想详细展示

**Comment by lete114** [comment]
> 可以通过a标签属性来控制显示的信息量大小么，有的链接想精简展示，但有的链接，想详细展示

可以是可以，但是我觉得这没必要
