### ISSUE TITLE
把这个做成一个hexo 插件以便更好的支持和集成？

### ISSUE THREAD

**Issue by appotry** [Lete114/CardLink#3]
插件在本地就获取到了生成卡片的图片，描叙信息

并且可以用tag标签精确控制那些链接生成carklink

这样，跨域主要可能产生在图片，那么用`https://images.weserv.nl?url=`这样转接显示

思路应该可行吧

**Comment by lete114** [comment]
没明白你的意思

**Comment by lete114** [comment]
> 跨域主要可能产生在图片，那么用`https://images.weserv.nl?url=`这样转接显示

img标签无视跨域问题，所以即使有跨域，对img标签无影响

**Comment by appotry** [comment]
web外行，本地插件获取链接信息，生成卡片插入文章，怎么样？

有个url 卡片 插件可以参考

[hexo-valkyr-url](https://github.com/toastsgithub/hexo-valkyr-url)

**Comment by lete114** [comment]
本仓库只能运行在浏览器端

**Comment by lete114** [comment]
无法在nodejs中运行

**Comment by appotry** [comment]
太遗憾了，我还以为是类似爬虫采集获取信息的

**Comment by lete114** [comment]
如果你想在hexo中使用你可以这样做

```html
<!-- 引入 js -->
<script src="cardlink.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', cardLink)
</script>
```
假设你已经在你的hexo博客主题上正确引入 cardLink，然后再文章的markdown中编写

```md

// 文章内容....

<a href="https://blog.imlete.cn" cardlink target="_blank">blog.imlete.cn</a>

// 文章内容...
```

**Comment by lete114** [comment]
这种写法兼容性更高，如果使用[hexo-valkyr-url](https://github.com/toastsgithub/hexo-valkyr-url)的话它的格式并非markdown的格式，而是hexo插件规定的语法解析后生成的，如果你未来要迁移到其它博客系统，其它博客系统无法识别[hexo-valkyr-url](https://github.com/toastsgithub/hexo-valkyr-url)的语法

**Comment by appotry** [comment]
[hexo-valkyr-url](https://github.com/toastsgithub/hexo-valkyr-url) 是不理想，两者优点能集合到一起就更好了

看我使用效果 [URL卡片](https://blog.17lai.site/posts/cf0f47fd/#URL-%E5%8D%A1%E7%89%87l)

能实现一个简单爬虫插件，爬取链接信息，生成[hexo-valkyr-url](https://github.com/toastsgithub/hexo-valkyr-url) 类似卡片是最理想的

兼容，只能说美观和兼容不可兼得，markdown语法都有不同标准，个人笔记，就全markdown，作为展示的blog，美观就更重要一些了，牺牲兼容是可以谅解的

**Comment by lete114** [comment]
你是想再本地构建的时候爬取指定链接网站的信息做成卡片后生成html文件吗？

**Comment by lete114** [comment]
如果是这样的话，文章很多的话，请求量就会增大，设置可能在请求的时候产生错误，这样会影响构建速度

**Comment by appotry** [comment]
> 如果是这样的话，那么文章多了，请求量就会增大，设置可能在请求的时候产生错误，这样会影响构建速度

可以建立一个缓存系统 前段时间建议douban插件加入缓存系统  https://github.com/TankNee/hexo-douban-card/issues/17

缓存到本地，优先本地查找，找不到再网络查找

这样就不会影响构建速度了，最终网页速度，体验也更好一些

**Comment by appotry** [comment]
缓存到本地之后，还可以手动修改某些信息为自定义内容，这样体验就更棒了

**Comment by lete114** [comment]
嗯，你感兴趣可以自己写个hexo插件，hexo与本仓库无关

**Comment by appotry** [comment]
想搞，但可惜个人js不擅长，不是主力编码语言

**Comment by lete114** [comment]
我觉得在CardLink浏览器端做挺好的，首先它不受任何形式的网站影响，可兼容性大部分网站

如果要做成服务端或客户端形式，那么用一套代码实现是不可能的

比如: 本身是用python做的爬虫抓取网站信息，那么就只能在python语言中使用并不能在java，go，nodejs等语言中使用，除非每个语言都要实现一遍，这样一来维护成本太高

**Comment by lete114** [comment]
另外，知乎也有卡片式链接，它并不是后端做的，而是去请求一个api，让服务端去爬取目标网站的相关信息最后返回给浏览器(为了解决跨域问题)，通过js生成卡片式链接，填充后端反回的信息，最后渲染到页面上
