### ISSUE TITLE
请问大佬能不能做一个极简版

### ISSUE THREAD

**Issue by xaoxuu** [Lete114/CardLink#4]
不含`css`，不`createElement`，只对约定字段填充数据，这样UI和数据解绑了，这样我可以在主题中直接内置这个插件。

> 如果不明白意思，可以参考一下这个： [ghrepo](https://github.com/xaoxuu/hexo-theme-stellar/blob/8301b75ee290d7cdea9cb8ba8ef8aec83aec7144/source/js/plugins/ghinfo.js#L49-L51)

**Comment by lete114** [comment]
你是想只让CardLink获取信息并返回，然后通过CardLink返回的数据在自己的代码中渲染自定义的模板吗？

**Comment by xaoxuu** [comment]
是的

**Comment by lete114** [comment]
这样的话，请求目标网站时是异步的，CardLink一开始可能会给你返回一个空的对象`{}`在CardLink处理完成后才会对该对象进行操作修改，所以我觉得这个可能性很小，你有什么好的方案吗？

**Comment by lete114** [comment]
要不你就把CardLink获取信息的代码抄过去，自己改改

**Comment by xaoxuu** [comment]
好的，那我就光明正大的copy了
