### ISSUE TITLE
网站引用后，我的内链就和外链无法区分了

### ISSUE THREAD

**Issue by wulintang** [Lete114/CardLink#7]
![1](https://user-images.githubusercontent.com/17123583/203731880-092bbd0b-87d8-4f5e-95b7-ae5ea8c43142.png)
如图所示，网站内，我的标签全部是自动内链的，外链的弄成卡片样式了，内链也跟着变了，我单独设置外链变成卡片样式好像也没有用。

**Comment by wulintang** [comment]
![2](https://user-images.githubusercontent.com/17123583/203732517-f739d69b-bf25-4f18-b4e7-ee1c55c84f2f.png)
我单独设置需要卡片式的url的class为url然后js如下
![3](https://user-images.githubusercontent.com/17123583/203732686-34fb9fd0-63b2-4526-8007-0481b963a5c9.png)
前端没有展示任何，没有展示卡片样式
![4](https://user-images.githubusercontent.com/17123583/203732868-94a13e37-eae9-48de-83fd-373d9690ddd4.png)

**Comment by wulintang** [comment]
cardLink(document.querySelectorAll('.single:not(a.tagslink) a[target=_blank]'))
我这样排除也排除不了么

**Comment by lete114** [comment]
这个你写错了
建议写成: `cardLink(document.querySelectorAll('a[target=_blank].url'))`
![](https://user-images.githubusercontent.com/17123583/203732686-34fb9fd0-63b2-4526-8007-0481b963a5c9.png)

**Comment by wulintang** [comment]
> 

是啊，我把问题想复杂了，谢谢老大，我已经成功了。

**Comment by wulintang** [comment]
如果多个class想用这个插件该怎么实现。

**Comment by lete114** [comment]
> 如果多个class想用这个插件该怎么实现。

描述具体点
