### ISSUE TITLE
部分网站乱码

### ISSUE THREAD

**Issue by wulintang** [Lete114/CardLink#8]
![image](https://user-images.githubusercontent.com/17123583/204090758-f6a6a1a9-b027-43ae-ad27-50ae8a77ab99.png)
搜狐体系新浪体系阿里体系的很多网站，都是乱码。

**Comment by lete114** [comment]
请提供一下地址

**Comment by wulintang** [comment]
http://mt.sohu.com

**Comment by wulintang** [comment]
![image](https://user-images.githubusercontent.com/17123583/204092552-f4b1cf3e-4f00-4d65-9181-415fac4afda0.png)

**Comment by lete114** [comment]
这个CardLink没法解决，因为
默认发送的请求是utf-8编码，而这个网站实际响应的是gbk编码，编码不一致所以导致的乱码
